config/routes.rb
Rails.application.routes.draw do
  resources :users do
    collection do
      get "count"
    end
    member do
      get "address"
    end
  end
  resources :merchants, only: [ :index, :create ] do
    resources :products, only: [ :create, :show ]
    resources :orders, only: [ :index, :new, :create, :show, :update ]
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  field :phone, type: String
  field :age, type: Integer
  field :address, type: Hash, default: {}
  field :order_count, type: Integer

  validates :name,
             presence: true
  validates :phone, 
             presence: true,
             length: { is: 10 },
             uniqueness: true
  validates :age, 
             numericality: { greater_than: 0 }
  validates :order_count, 
             numericality: { greater_than_or_equal_to: 0 }

  belongs_to :merchant, optional: true
  has_many :orders

  
  def update_order_count
    order_count = self.orders.where(:status.nin => [ "cancelled" ]).count
    self.update(order_count: order_count)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_user, only: %i[ show edit update destroy address ]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def count
    users_count = User.count
    render json: users_count, status:200
  end

  def address
    address = "#{@user.address[:country]} #{@user.address[:address_1]} #{@user.address[:address_2]}"
    render json: address, status:200
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :phone, :age, :order_count, address: [:country, :address_1, :address_2])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.fields_for :address do |address_builder| %>
      <%= address_builder.label :country %>
      <%= address_builder.text_field :country %>
      <%= address_builder.label :address_1 %>
      <%= address_builder.text_field :address_1 %>
      <%= address_builder.label :address_2 %>
      <%= address_builder.text_field :address_2 %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :order_count %>
    <%= form.number_field :order_count %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Age</th>
      <th>Order count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.phone %></td>
        <td><%= user.age %></td>
        <td><%= user.order_count %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Address', address_user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<%= link_to 'Total Number of User', count_users_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address[:country] %>
  <%= @user.address[:address_1] %>
  <%= @user.address[:address_2] %>
</p>

<p>
  <strong>Order count:</strong>
  <%= @user.order_count %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>