config/routes.rb
Rails.application.routes.draw do
  resources :users do
    collection do
      get "count"
    end
    member do
      get "address"
    end
  end
  resources :merchants, only: [ :index, :create ] do
    resources :products, only: [ :create, :show ]
    resources :orders, only: [ :index, :new, :create, :show, :update ]
  end
end

app/models/order.rb
class Order
  include Mongoid::Document
  include Mongoid::Timestamps
  field :status, type: String, default: "pending"
  field :customer_name, type: String
  field :customer_phone, type: String
  field :confirmed_at, type: DateTime
  field :completed_at, type: DateTime
  field :cancelled_at, type: DateTime

  validates_inclusion_of :status, in: %w(pending confirmed completed cancelled)

  belongs_to :user, optional: true
  has_many :order_items
  accepts_nested_attributes_for :order_items

  before_update :update_related_status_time, if: :status_changed?
  before_save :establish_relation_with_user
  after_save :update_user_order_count
  
  searchkick
  
  def search_data
    {
      customer_name: customer_name,
      customer_phone: customer_phone
    }
  end
  
  def create_orderitems(order_items_params)
    order_items_params.each do |order_item_params|
      item = Object.const_get(order_item_params[:item_type]).find(order_item_params[:item_id])
      if item.present?
        self.order_items.create(item_id: order_item_params[:item_id],
                                item_type: order_item_params[:item_type], 
                                object_data: item.attributes, 
                                quantity: order_item_params[:quantity],
                                variation_id: order_item_params[:variation_id])
      end
    end
  end
  
  private
  def update_related_status_time
    case self.status
    when "confirmed"
      self.confirmed_at = Time.zone.now
    when "completed"
      self.completed_at = Time.zone.now
    when "cancelled"
      self.cancelled_at = Time.zone.now
    end
  end

  def update_user_order_count
    if user.present? && self.status_changed?
      user.update_order_count
    end
  end

  def establish_relation_with_user
    user = User.find_by(phone: customer_phone)
    if user.present?
      self.user = user
    end 
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_order, only: [ :show, :update ]
  
  def index
    @orders = Order.all
    render json: { order: @orders }, status: 200
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    
    if @order.save
      @order.create_orderitems(order_params[:order_items_attributes])
      render json: { order: @order, order_items: @order.order_items, user: @order.user }, status: 201
    else
      render json: { error: @order.errors }, status: 422
    end
  end

  def show
    render json: { order: @order, order_items: @order.order_items }, status: 200
  end

  def update
    if @order.update(status_params)
      render json: { order: @order, user: @order.user }, status: 201
    else
      render json: { error: @order.errors }, status: 422
    end
  end

  private
  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:status,
                                  :customer_name,
                                  :customer_phone,
                                  order_items_attributes: [ :item_id, :item_type, :quantity, :variation_id])
  end

  def status_params
    params.require(:order).permit(:status)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/new.html.erb
<%= form_with(model: @order, url: merchant_orders_path) do |form| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% @order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_name %>
    <%= form.text_field :customer_name %>
  </div>

  <div class="field">
    <%= form.label :customer_phone %>
    <%= form.text_field :customer_phone %>
  </div>

  <div class="field">
    <%= form.label :order_item %>
    <%= form.fields_for :order_item do |item_attributes| %>
      <%= item_attributes.label :item_id %>
      <%= item_attributes.text_field :item_id %>
      <%= item_attributes.label :item_type %>
      <%= item_attributes.text_field :item_type %>
      <%= item_attributes.label :quantity %>
      <%= item_attributes.text_field :quantity %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>