config/routes.rb
Rails.application.routes.draw do
  resources :users do
    collection do
      get "count"
    end
    member do
      get "address"
    end
  end
  resources :merchants, only: [ :index, :create ] do
    resources :products, only: [ :create, :show ]
    resources :orders, only: [ :index, :new, :create, :show, :update ]
  end
end

app/models/merchant.rb
class Merchant
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  field :shop_status, type: String, default: "open"

  validates :name,
             presence: true
  
  has_many :users
  has_many :products
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  protect_from_forgery with: :null_session

  def index
    @merchants = Merchant.all
  end

  def create
    merchant = Merchant.new(merchant_params)
    if merchant.save
      render json: merchant, status: 201
    else
      render json: merchant.errors, status: 422
    end
  end

  private
  def merchant_params
    params.require(:merchant).permit(:name, :shop_status)
  end
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/merchants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Merchants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Shop_status</th>
    </tr>
  </thead>

  <tbody>
    <% @merchants.each do |merchant| %>
      <tr>
        <td><%= merchant.name %></td>
        <td><%= merchant.shop_status %></td>
        <td><%= link_to 'Product', merchant_products_path(merchant) %></td>
      </tr>
    <% end %>
  </tbody>
</table>